#!/bin/bash --login
#PBS  -l walltime=01:00:00
#PBS -l select=1:ncpus=8
#PBS -N 2018_data_core_diversity
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
#core diverisity analysis
core_diversity_analyses.py -o cdout -i otus/otu_table.biom -m 2018_02_smb/map.tsv -t otus/97_otus.tree -e 18284 
source deactivate
