#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=4
#PBS -N 2018_compare
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
group_significance.py  -i /lustre/home/d411/zcbtaol/otus/otu_table.biom -m map.txt -c SamplePh -o groupsig.txt
source deactivate
