#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=16
#PBS -N _2017_cr_nojoin_no_golay_parallel
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
jackknifed_beta_diversity.py -i otus/otu_table.biom -m map.tsv -t otus/97_otus.tree -e 18284 -o jackout
source deactivate
