#!/bin/bash --login
#PBS  -l walltime=01:00:00
#PBS -l select=1:ncpus=8
#PBS -N 2018_new_try_split_pick2
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# splitting libraries
echo "splitting libraries"
time split_libraries_fastq.py --barcode_type 12 -i Read1.fastq.gz -b Index.fastq.gz -o slout -m map.tsv
# counting sequences
echo "Counting sequences"
time count_seqs.py -i slout/seqs.fna
# picking OTUs
echo "Picking OTUs with open reference"
time pick_closed_reference_otus.py -i slout/seqs.fna -o otus -a\
-O 16
source deactivate
